// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/parcel.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	v1 "backend/api/v1"
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockParcelService is a mock of ParcelService interface.
type MockParcelService struct {
	ctrl     *gomock.Controller
	recorder *MockParcelServiceMockRecorder
}

// MockParcelServiceMockRecorder is the mock recorder for MockParcelService.
type MockParcelServiceMockRecorder struct {
	mock *MockParcelService
}

// NewMockParcelService creates a new mock instance.
func NewMockParcelService(ctrl *gomock.Controller) *MockParcelService {
	mock := &MockParcelService{ctrl: ctrl}
	mock.recorder = &MockParcelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParcelService) EXPECT() *MockParcelServiceMockRecorder {
	return m.recorder
}

// GetDashboardStatistics mocks base method.
func (m *MockParcelService) GetDashboardStatistics(ctx context.Context) (*v1.DashboardStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardStatistics", ctx)
	ret0, _ := ret[0].(*v1.DashboardStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardStatistics indicates an expected call of GetDashboardStatistics.
func (mr *MockParcelServiceMockRecorder) GetDashboardStatistics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardStatistics", reflect.TypeOf((*MockParcelService)(nil).GetDashboardStatistics), ctx)
}

// GetMyParcels mocks base method.
func (m *MockParcelService) GetMyParcels(ctx context.Context, phone string, req *v1.ParcelListRequest) (*v1.ParcelListData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyParcels", ctx, phone, req)
	ret0, _ := ret[0].(*v1.ParcelListData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyParcels indicates an expected call of GetMyParcels.
func (mr *MockParcelServiceMockRecorder) GetMyParcels(ctx, phone, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyParcels", reflect.TypeOf((*MockParcelService)(nil).GetMyParcels), ctx, phone, req)
}

// GetParcelByPickupCode mocks base method.
func (m *MockParcelService) GetParcelByPickupCode(ctx context.Context, pickupCode string) (*model.Parcel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParcelByPickupCode", ctx, pickupCode)
	ret0, _ := ret[0].(*model.Parcel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParcelByPickupCode indicates an expected call of GetParcelByPickupCode.
func (mr *MockParcelServiceMockRecorder) GetParcelByPickupCode(ctx, pickupCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParcelByPickupCode", reflect.TypeOf((*MockParcelService)(nil).GetParcelByPickupCode), ctx, pickupCode)
}

// GetParcelByTrackingNumber mocks base method.
func (m *MockParcelService) GetParcelByTrackingNumber(ctx context.Context, trackingNumber string) (*model.Parcel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParcelByTrackingNumber", ctx, trackingNumber)
	ret0, _ := ret[0].(*model.Parcel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParcelByTrackingNumber indicates an expected call of GetParcelByTrackingNumber.
func (mr *MockParcelServiceMockRecorder) GetParcelByTrackingNumber(ctx, trackingNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParcelByTrackingNumber", reflect.TypeOf((*MockParcelService)(nil).GetParcelByTrackingNumber), ctx, trackingNumber)
}

// GetParcelList mocks base method.
func (m *MockParcelService) GetParcelList(ctx context.Context, req *v1.ParcelListRequest) (*v1.ParcelListData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParcelList", ctx, req)
	ret0, _ := ret[0].(*v1.ParcelListData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParcelList indicates an expected call of GetParcelList.
func (mr *MockParcelServiceMockRecorder) GetParcelList(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParcelList", reflect.TypeOf((*MockParcelService)(nil).GetParcelList), ctx, req)
}

// PickupParcel mocks base method.
func (m *MockParcelService) PickupParcel(ctx context.Context, req *v1.PickupParcelRequest) (*model.Parcel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PickupParcel", ctx, req)
	ret0, _ := ret[0].(*model.Parcel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PickupParcel indicates an expected call of PickupParcel.
func (mr *MockParcelServiceMockRecorder) PickupParcel(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PickupParcel", reflect.TypeOf((*MockParcelService)(nil).PickupParcel), ctx, req)
}

// ReceiveParcel mocks base method.
func (m *MockParcelService) ReceiveParcel(ctx context.Context, req *v1.ReceiveParcelRequest) (*model.Parcel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveParcel", ctx, req)
	ret0, _ := ret[0].(*model.Parcel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveParcel indicates an expected call of ReceiveParcel.
func (mr *MockParcelServiceMockRecorder) ReceiveParcel(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveParcel", reflect.TypeOf((*MockParcelService)(nil).ReceiveParcel), ctx, req)
}

// ShelveParcel mocks base method.
func (m *MockParcelService) ShelveParcel(ctx context.Context, id int64) (*model.Parcel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShelveParcel", ctx, id)
	ret0, _ := ret[0].(*model.Parcel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShelveParcel indicates an expected call of ShelveParcel.
func (mr *MockParcelServiceMockRecorder) ShelveParcel(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShelveParcel", reflect.TypeOf((*MockParcelService)(nil).ShelveParcel), ctx, id)
}
