// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/shipment.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	v1 "backend/api/v1"
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShipmentService is a mock of ShipmentService interface.
type MockShipmentService struct {
	ctrl     *gomock.Controller
	recorder *MockShipmentServiceMockRecorder
}

// MockShipmentServiceMockRecorder is the mock recorder for MockShipmentService.
type MockShipmentServiceMockRecorder struct {
	mock *MockShipmentService
}

// NewMockShipmentService creates a new mock instance.
func NewMockShipmentService(ctrl *gomock.Controller) *MockShipmentService {
	mock := &MockShipmentService{ctrl: ctrl}
	mock.recorder = &MockShipmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShipmentService) EXPECT() *MockShipmentServiceMockRecorder {
	return m.recorder
}

// CalculateFreight mocks base method.
func (m *MockShipmentService) CalculateFreight(ctx context.Context, req *v1.CalculateFreightRequest) (*v1.CalculateFreightData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateFreight", ctx, req)
	ret0, _ := ret[0].(*v1.CalculateFreightData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateFreight indicates an expected call of CalculateFreight.
func (mr *MockShipmentServiceMockRecorder) CalculateFreight(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateFreight", reflect.TypeOf((*MockShipmentService)(nil).CalculateFreight), ctx, req)
}

// CreateShipment mocks base method.
func (m *MockShipmentService) CreateShipment(ctx context.Context, senderID int64, senderName, senderPhone string, req *v1.CreateShipmentRequest) (*model.Shipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShipment", ctx, senderID, senderName, senderPhone, req)
	ret0, _ := ret[0].(*model.Shipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShipment indicates an expected call of CreateShipment.
func (mr *MockShipmentServiceMockRecorder) CreateShipment(ctx, senderID, senderName, senderPhone, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShipment", reflect.TypeOf((*MockShipmentService)(nil).CreateShipment), ctx, senderID, senderName, senderPhone, req)
}

// GetCourierCompanies mocks base method.
func (m *MockShipmentService) GetCourierCompanies(ctx context.Context) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierCompanies", ctx)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetCourierCompanies indicates an expected call of GetCourierCompanies.
func (mr *MockShipmentServiceMockRecorder) GetCourierCompanies(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierCompanies", reflect.TypeOf((*MockShipmentService)(nil).GetCourierCompanies), ctx)
}

// GetMyShipments mocks base method.
func (m *MockShipmentService) GetMyShipments(ctx context.Context, senderID int64, req *v1.ShipmentListRequest) (*v1.ShipmentListData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyShipments", ctx, senderID, req)
	ret0, _ := ret[0].(*v1.ShipmentListData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyShipments indicates an expected call of GetMyShipments.
func (mr *MockShipmentServiceMockRecorder) GetMyShipments(ctx, senderID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyShipments", reflect.TypeOf((*MockShipmentService)(nil).GetMyShipments), ctx, senderID, req)
}

// GetShipmentByID mocks base method.
func (m *MockShipmentService) GetShipmentByID(ctx context.Context, id int64) (*model.Shipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShipmentByID", ctx, id)
	ret0, _ := ret[0].(*model.Shipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShipmentByID indicates an expected call of GetShipmentByID.
func (mr *MockShipmentServiceMockRecorder) GetShipmentByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShipmentByID", reflect.TypeOf((*MockShipmentService)(nil).GetShipmentByID), ctx, id)
}
