// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/parcel.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockParcelRepository is a mock of ParcelRepository interface.
type MockParcelRepository struct {
	ctrl     *gomock.Controller
	recorder *MockParcelRepositoryMockRecorder
}

// MockParcelRepositoryMockRecorder is the mock recorder for MockParcelRepository.
type MockParcelRepositoryMockRecorder struct {
	mock *MockParcelRepository
}

// NewMockParcelRepository creates a new mock instance.
func NewMockParcelRepository(ctrl *gomock.Controller) *MockParcelRepository {
	mock := &MockParcelRepository{ctrl: ctrl}
	mock.recorder = &MockParcelRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParcelRepository) EXPECT() *MockParcelRepositoryMockRecorder {
	return m.recorder
}

// CountByStatus mocks base method.
func (m *MockParcelRepository) CountByStatus(ctx context.Context) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", ctx)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockParcelRepositoryMockRecorder) CountByStatus(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockParcelRepository)(nil).CountByStatus), ctx)
}

// CountOverdue mocks base method.
func (m *MockParcelRepository) CountOverdue(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOverdue", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOverdue indicates an expected call of CountOverdue.
func (mr *MockParcelRepositoryMockRecorder) CountOverdue(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOverdue", reflect.TypeOf((*MockParcelRepository)(nil).CountOverdue), ctx)
}

// CountTodayPickedUp mocks base method.
func (m *MockParcelRepository) CountTodayPickedUp(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTodayPickedUp", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTodayPickedUp indicates an expected call of CountTodayPickedUp.
func (mr *MockParcelRepositoryMockRecorder) CountTodayPickedUp(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTodayPickedUp", reflect.TypeOf((*MockParcelRepository)(nil).CountTodayPickedUp), ctx)
}

// CountTodayReceived mocks base method.
func (m *MockParcelRepository) CountTodayReceived(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTodayReceived", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTodayReceived indicates an expected call of CountTodayReceived.
func (mr *MockParcelRepositoryMockRecorder) CountTodayReceived(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTodayReceived", reflect.TypeOf((*MockParcelRepository)(nil).CountTodayReceived), ctx)
}

// Create mocks base method.
func (m *MockParcelRepository) Create(ctx context.Context, parcel *model.Parcel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, parcel)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockParcelRepositoryMockRecorder) Create(ctx, parcel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParcelRepository)(nil).Create), ctx, parcel)
}

// GetByID mocks base method.
func (m *MockParcelRepository) GetByID(ctx context.Context, id int64) (*model.Parcel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Parcel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockParcelRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockParcelRepository)(nil).GetByID), ctx, id)
}

// GetByPickupCode mocks base method.
func (m *MockParcelRepository) GetByPickupCode(ctx context.Context, pickupCode string) (*model.Parcel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPickupCode", ctx, pickupCode)
	ret0, _ := ret[0].(*model.Parcel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPickupCode indicates an expected call of GetByPickupCode.
func (mr *MockParcelRepositoryMockRecorder) GetByPickupCode(ctx, pickupCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPickupCode", reflect.TypeOf((*MockParcelRepository)(nil).GetByPickupCode), ctx, pickupCode)
}

// GetByTrackingNumber mocks base method.
func (m *MockParcelRepository) GetByTrackingNumber(ctx context.Context, trackingNumber string) (*model.Parcel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTrackingNumber", ctx, trackingNumber)
	ret0, _ := ret[0].(*model.Parcel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTrackingNumber indicates an expected call of GetByTrackingNumber.
func (mr *MockParcelRepositoryMockRecorder) GetByTrackingNumber(ctx, trackingNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTrackingNumber", reflect.TypeOf((*MockParcelRepository)(nil).GetByTrackingNumber), ctx, trackingNumber)
}

// GetRecentTrends mocks base method.
func (m *MockParcelRepository) GetRecentTrends(ctx context.Context, days int) ([]map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentTrends", ctx, days)
	ret0, _ := ret[0].([]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentTrends indicates an expected call of GetRecentTrends.
func (mr *MockParcelRepositoryMockRecorder) GetRecentTrends(ctx, days interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentTrends", reflect.TypeOf((*MockParcelRepository)(nil).GetRecentTrends), ctx, days)
}

// List mocks base method.
func (m *MockParcelRepository) List(ctx context.Context, status, courierCompany, recipientPhone string, page, pageSize int) ([]*model.Parcel, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, status, courierCompany, recipientPhone, page, pageSize)
	ret0, _ := ret[0].([]*model.Parcel)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockParcelRepositoryMockRecorder) List(ctx, status, courierCompany, recipientPhone, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockParcelRepository)(nil).List), ctx, status, courierCompany, recipientPhone, page, pageSize)
}

// ListByRecipientPhone mocks base method.
func (m *MockParcelRepository) ListByRecipientPhone(ctx context.Context, phone, status string, page, pageSize int) ([]*model.Parcel, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRecipientPhone", ctx, phone, status, page, pageSize)
	ret0, _ := ret[0].([]*model.Parcel)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByRecipientPhone indicates an expected call of ListByRecipientPhone.
func (mr *MockParcelRepositoryMockRecorder) ListByRecipientPhone(ctx, phone, status, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRecipientPhone", reflect.TypeOf((*MockParcelRepository)(nil).ListByRecipientPhone), ctx, phone, status, page, pageSize)
}

// Update mocks base method.
func (m *MockParcelRepository) Update(ctx context.Context, parcel *model.Parcel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, parcel)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockParcelRepositoryMockRecorder) Update(ctx, parcel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockParcelRepository)(nil).Update), ctx, parcel)
}
