// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/shelf.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShelfRepository is a mock of ShelfRepository interface.
type MockShelfRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShelfRepositoryMockRecorder
}

// MockShelfRepositoryMockRecorder is the mock recorder for MockShelfRepository.
type MockShelfRepositoryMockRecorder struct {
	mock *MockShelfRepository
}

// NewMockShelfRepository creates a new mock instance.
func NewMockShelfRepository(ctrl *gomock.Controller) *MockShelfRepository {
	mock := &MockShelfRepository{ctrl: ctrl}
	mock.recorder = &MockShelfRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShelfRepository) EXPECT() *MockShelfRepositoryMockRecorder {
	return m.recorder
}

// CountActive mocks base method.
func (m *MockShelfRepository) CountActive(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActive", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActive indicates an expected call of CountActive.
func (mr *MockShelfRepositoryMockRecorder) CountActive(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActive", reflect.TypeOf((*MockShelfRepository)(nil).CountActive), ctx)
}

// CountByType mocks base method.
func (m *MockShelfRepository) CountByType(ctx context.Context) ([]map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByType", ctx)
	ret0, _ := ret[0].([]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByType indicates an expected call of CountByType.
func (mr *MockShelfRepositoryMockRecorder) CountByType(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByType", reflect.TypeOf((*MockShelfRepository)(nil).CountByType), ctx)
}

// Create mocks base method.
func (m *MockShelfRepository) Create(ctx context.Context, shelf *model.Shelf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, shelf)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockShelfRepositoryMockRecorder) Create(ctx, shelf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShelfRepository)(nil).Create), ctx, shelf)
}

// DecrementCount mocks base method.
func (m *MockShelfRepository) DecrementCount(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementCount", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementCount indicates an expected call of DecrementCount.
func (mr *MockShelfRepositoryMockRecorder) DecrementCount(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementCount", reflect.TypeOf((*MockShelfRepository)(nil).DecrementCount), ctx, id)
}

// Delete mocks base method.
func (m *MockShelfRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShelfRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShelfRepository)(nil).Delete), ctx, id)
}

// FindAvailableShelfByType mocks base method.
func (m *MockShelfRepository) FindAvailableShelfByType(ctx context.Context, shelfType model.ShelfType) (*model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailableShelfByType", ctx, shelfType)
	ret0, _ := ret[0].(*model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailableShelfByType indicates an expected call of FindAvailableShelfByType.
func (mr *MockShelfRepositoryMockRecorder) FindAvailableShelfByType(ctx, shelfType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailableShelfByType", reflect.TypeOf((*MockShelfRepository)(nil).FindAvailableShelfByType), ctx, shelfType)
}

// GetByID mocks base method.
func (m *MockShelfRepository) GetByID(ctx context.Context, id int64) (*model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockShelfRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockShelfRepository)(nil).GetByID), ctx, id)
}

// GetByShelfCode mocks base method.
func (m *MockShelfRepository) GetByShelfCode(ctx context.Context, shelfCode string) (*model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShelfCode", ctx, shelfCode)
	ret0, _ := ret[0].(*model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByShelfCode indicates an expected call of GetByShelfCode.
func (mr *MockShelfRepositoryMockRecorder) GetByShelfCode(ctx, shelfCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShelfCode", reflect.TypeOf((*MockShelfRepository)(nil).GetByShelfCode), ctx, shelfCode)
}

// GetStatistics mocks base method.
func (m *MockShelfRepository) GetStatistics(ctx context.Context) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockShelfRepositoryMockRecorder) GetStatistics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockShelfRepository)(nil).GetStatistics), ctx)
}

// IncrementCount mocks base method.
func (m *MockShelfRepository) IncrementCount(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCount", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementCount indicates an expected call of IncrementCount.
func (mr *MockShelfRepositoryMockRecorder) IncrementCount(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCount", reflect.TypeOf((*MockShelfRepository)(nil).IncrementCount), ctx, id)
}

// List mocks base method.
func (m *MockShelfRepository) List(ctx context.Context, area, shelfType, status string, page, pageSize int) ([]*model.Shelf, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, area, shelfType, status, page, pageSize)
	ret0, _ := ret[0].([]*model.Shelf)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockShelfRepositoryMockRecorder) List(ctx, area, shelfType, status, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockShelfRepository)(nil).List), ctx, area, shelfType, status, page, pageSize)
}

// Update mocks base method.
func (m *MockShelfRepository) Update(ctx context.Context, shelf *model.Shelf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, shelf)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockShelfRepositoryMockRecorder) Update(ctx, shelf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShelfRepository)(nil).Update), ctx, shelf)
}
