// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/shipment.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShipmentRepository is a mock of ShipmentRepository interface.
type MockShipmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShipmentRepositoryMockRecorder
}

// MockShipmentRepositoryMockRecorder is the mock recorder for MockShipmentRepository.
type MockShipmentRepositoryMockRecorder struct {
	mock *MockShipmentRepository
}

// NewMockShipmentRepository creates a new mock instance.
func NewMockShipmentRepository(ctrl *gomock.Controller) *MockShipmentRepository {
	mock := &MockShipmentRepository{ctrl: ctrl}
	mock.recorder = &MockShipmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShipmentRepository) EXPECT() *MockShipmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShipmentRepository) Create(ctx context.Context, shipment *model.Shipment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, shipment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockShipmentRepositoryMockRecorder) Create(ctx, shipment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShipmentRepository)(nil).Create), ctx, shipment)
}

// GetByID mocks base method.
func (m *MockShipmentRepository) GetByID(ctx context.Context, id int64) (*model.Shipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Shipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockShipmentRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockShipmentRepository)(nil).GetByID), ctx, id)
}

// GetByShipmentNumber mocks base method.
func (m *MockShipmentRepository) GetByShipmentNumber(ctx context.Context, shipmentNumber string) (*model.Shipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShipmentNumber", ctx, shipmentNumber)
	ret0, _ := ret[0].(*model.Shipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByShipmentNumber indicates an expected call of GetByShipmentNumber.
func (mr *MockShipmentRepositoryMockRecorder) GetByShipmentNumber(ctx, shipmentNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShipmentNumber", reflect.TypeOf((*MockShipmentRepository)(nil).GetByShipmentNumber), ctx, shipmentNumber)
}

// ListBySenderID mocks base method.
func (m *MockShipmentRepository) ListBySenderID(ctx context.Context, senderID int64, status string, page, pageSize int) ([]*model.Shipment, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySenderID", ctx, senderID, status, page, pageSize)
	ret0, _ := ret[0].([]*model.Shipment)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBySenderID indicates an expected call of ListBySenderID.
func (mr *MockShipmentRepositoryMockRecorder) ListBySenderID(ctx, senderID, status, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySenderID", reflect.TypeOf((*MockShipmentRepository)(nil).ListBySenderID), ctx, senderID, status, page, pageSize)
}

// Update mocks base method.
func (m *MockShipmentRepository) Update(ctx context.Context, shipment *model.Shipment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, shipment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockShipmentRepositoryMockRecorder) Update(ctx, shipment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShipmentRepository)(nil).Update), ctx, shipment)
}
