// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend/internal/handler"
	"backend/internal/job"
	"backend/internal/repository"
	"backend/internal/router"
	"backend/internal/server"
	"backend/internal/service"
	"backend/pkg/app"
	"backend/pkg/jwt"
	"backend/pkg/log"
	"backend/pkg/server/http"
	"backend/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	handlerHandler := handler.NewHandler(logger, userService)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	parcelRepository := repository.NewParcelRepository(repositoryRepository)
	shelfRepository := repository.NewShelfRepository(repositoryRepository)
	parcelService := service.NewParcelService(parcelRepository, shelfRepository, transaction)
	parcelHandler := handler.NewParcelHandler(handlerHandler, parcelService)
	shipmentRepository := repository.NewShipmentRepository(repositoryRepository)
	shipmentService := service.NewShipmentService(shipmentRepository)
	shipmentHandler := handler.NewShipmentHandler(handlerHandler, shipmentService)
	routerDeps := router.RouterDeps{
		Logger:          logger,
		Config:          viperViper,
		JWT:             jwtJWT,
		UserHandler:     userHandler,
		ParcelHandler:   parcelHandler,
		ShipmentHandler: shipmentHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewParcelRepository, repository.NewShelfRepository, repository.NewShipmentRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewParcelService, service.NewShipmentService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewParcelHandler, handler.NewShipmentHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("demo-server"))
}
